### ISSUE TITLE
feature request: non-binding margins version

### ISSUE THREAD

**Issue by hcientist** [ChrisMayfield/ThinkJava2#1]
might it be easy to have a slightly different stylesheet for pdf intended to be viewed on computer/printed but not bound? That is, the margins in the PDF i'm viewing are for book-binding, but maybe it'd be trivial to offer a version that doesn't have those margins for people who aren't binding it? (obviously not a huge priority)

**Comment by ChrisMayfield** [comment]
Another solution would be to build a "tablet version" like Pieter Spronck's book based on Think Python: http://www.spronck.net/pythonbook/.
