### ISSUE TITLE
 Describe Linux dependencies in README

### ISSUE THREAD

**Issue by ramalho** [ChrisMayfield/ThinkJava2#10]
In order to build the book on Ubuntu 16.04 I had to install the following packages:

-  texlive-latex-base (obvious)
-  texlive-latex-extra (aready mentioned in README.md)
-  texlive-fonts-recommended (not mentioned, but also needed)

**Comment by ChrisMayfield** [comment]
Thanks for the feedback, and sorry it took me so long.
