### ISSUE TITLE
Section 12.3 error with "final"

### ISSUE THREAD

**Issue by ceculbe** [ChrisMayfield/ThinkJava2#18]
Section 12.3 appears to contain an error in describing how "final" applies to arrays. It suggests that making the RANKS and SUITS arrays final will prevent their contents from being changed, and therefore they can even safely be made public:

> and final means the variable is constant.

> Since the array variables are final, and the strings they
> reference are immutable, there is no danger in making them public.

But since only the array reference itself is final, the String reference in each element is still subject to being reassigned. This code in a client class will show the behavior:
```
    Card c = new Card(1, 2);
    // Card.SUITS = new String[4];  // not allowed - array is final
    Card.SUITS[2] = "Oranges";  // allowed - elements of the array are not final
    System.out.println(c);
```
BTW, keep up  the great work! This book has been the starting point for so many of my students who have gone on to majors and careers in CS.

**Comment by ChrisMayfield** [comment]
Thank you for catching this issue! I'll try to fix it in the next release.
