### ISSUE TITLE
Warning: Command not found: \raisebox

### ISSUE THREAD

**Issue by will-crawford** [ChrisMayfield/ThinkJava2#19]
hevea 2.32
LaTeX2e <2018-04-01> patch level 5

./ch15.tex:57: Warning: Command not found: \raisebox
./ch15.tex:59: Warning: Command not found: \raisebox
./ch15.tex:61: Warning: Command not found: \raisebox

**Comment by ChrisMayfield** [comment]
Thank you -- I'll take a look next week.
