### ISSUE TITLE
Incorrect code sample in the section 6.9 Substrings

### ISSUE THREAD

**Issue by tunggnu** [ChrisMayfield/ThinkJava2#21]
The last paragraph of the section 6.9 says:

> We could also use `fruit.substring(2, fruit.length() - 1)` to get the
> result "nana". But calling substring with one argument is more convenient
> when you want the end of the string.

Also, in the section 6.8, `fruit` has been defined as `String fruit = "banana";`. So `fruit.substring(2, fruit.length() - 1)` will evaluate to "nan" instead of "nana". If we really want to get "nana', we have to use `fruit.substring(2, fruit.length())`.

**Comment by ChrisMayfield** [comment]
Nice catch! Thanks for the fix.

**Comment by ChrisMayfield** [comment]
Thanks again
