### ISSUE TITLE
Error in Explaining `substring()` method

### ISSUE THREAD

**Issue by ahmedaddous** [ChrisMayfield/ThinkJava2#24]
Hey! Could this be a possible mistake in the book?

> We could also use `fruit.substring(2, fruit.length() - 1)` to get the result `"nana"`. But calling substring with one argument is more convenient when you want the end of the string.

`fruit` is supposed to be a variable referring to the string `"banana"`, so wouldn't doing `fruit.substring(2, fruit.length() - 1)` actually leave off the last element, returning `"nan"`. This could be tested using this program:

```
class Main {
  public static void main(String[] args) {
    String fruit = "banana";

    System.out.println(
      fruit.substring(2, fruit.length() - 1)
    );
  }
}
``` 
This program prints out: `"nan"`, as was expected. But the author says it prints out `"nana"`. This issue could be found on page 100 of the completed book.

**Comment by ahmedaddous** [comment]
Oh! I just realized that this was realized in [here](https://github.com/ChrisMayfield/ThinkJava2/issues/21#issue-797784927). Sorry about the redundant notice!

**Comment by ChrisMayfield** [comment]
It's all good! Thanks for the feedback. One of these days we'll update the pdf/html builds on the website.
