### ISSUE TITLE
"floating point"

### ISSUE THREAD

**Issue by mhciael** [ChrisMayfield/ThinkJava2#3]
2.6 introduces floating points, 

>  A more general solution is to use floating-point numbers, which can represent fractions as well as integers. 

would it be clarifying somewhere to first call them `decimal numbers` or `numbers with decimals` `as you have seen in math/money/etc.`? I'm unsure that the students are understanding "fraction" in this context, because while mathematically equiv, fractions are usually denoted by what looks like an integer division operation

a number of my students on a quiz about this chpt, indicated they were a little muddy

> A weakness of the chapter that could use improvement however was describing double type.

**Comment by ChrisMayfield** [comment]
That's a great idea; will do during the next pass.
