### ISSUE TITLE
student feed back about figures in chpt 5 

### ISSUE THREAD

**Issue by mhciael** [ChrisMayfield/ThinkJava2#8]
A strength of this chapter was the diagram about passing the parameters and saving the return value (Figure 5.2). The arrows really helped me understand how values are passed through different methods and how the process works. I thought it was a little confusing how the whole chapter focused on one or two examples and I kept having to scroll back and forth to remind myself of what the method they were talking about looked like. It would have been more helpful to keep putting it all together or to use different examples.

**Comment by ChrisMayfield** [comment]
My thoughts exactly! I'm going to work some more on the methods chapter and POGIL activity over the break...hopefully.
